---
image: vm0915/ansible:a0.9

include:
  - template: Security/SAST.gitlab-ci.yml

stages:
  - lintcheck

yamllint:
  stage: lintcheck
  script:
    - yamllint .
  when: manual

ansible_lint:
  stage: lintcheck
  script:
    - ansible-lint
  when: manual
