# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
image: vm0915/ansible:a1.0
include:
- template: Security/Secret-Detection.gitlab-ci.yml
- template: Security/SAST-IaC.latest.gitlab-ci.yml
stages:
- test
- deploy
- lintcheck

secret_detection:
  when: manual
kics-iac-sast:
  when: manual

test:
  stage: test
  script:
  - echo "Testing"
  - echo $AWS_KEY
  when: manual

deploy:
  stage: deploy
  script:
    - echo pwd
    - echo $AWS_KEY
    - chmod 0600 $AWS_KEY
    - export ANSIBLE_CONFIG=`pwd`/ansible.cfg
    - ansible-playbook -i inventory/all.yml --private-key $AWS_KEY playbook2.yml --tags=python3
#  when: manual

yamllint:
  stage: lintcheck
  script:
  - yamllint .
  when: manual
ansible_lint:
  stage: lintcheck
  script:
  - ansible-lint
  when: manual
