stages:
  - lintcheck

lintcheck:
  stage: lintcheck
  image: vm0915/ansible:a0.8
  script:
    - whoami
    - id
    - echo ~
    - pwd
    - ls -lah
    - ls -lah /root
    - ls -lah /root/.config/yamllint
    - yamllint .
    - ansible-lint
