stages:
  - lintcheck

lintcheck:
  stage: lintcheck
  image: vm0915/ansible:a0.7
  script:
    - whoami
    - id
    - echo ~
    - pwd
    - ls -lah
    - ls -lah /root
    - yamllint 
    - ansible-lint
