---
image: vm0915/ansible:a0.9

stages:
  - lintcheck

yamllint:
  stage: lintcheck
  script:
    - yamllint .
  when: manual

ansible_lint:
  stage: lintcheck
  script:
    - ansible-lint
  when: manual
