---
- hosts: vm1
  become: true
  roles:
    - role: prometheus_docker
      tags: prometheus
      
    - role: grafana_docker
    - role: node_exporter
    - role: loki_docker
    - role: cadviser_docker
  vars: 
    ansible_python_interpreter: /usr/bin/python3
