---
all:
  children:
    servers:
      hosts:
        vm1:
          ansible_host: 192.168.0.101
          ansible_ssh_private_key_file: /home/user01/vms/.vagrant/machines/vm1/virtualbox/private_key
        vm2:
          ansible_host: 192.168.0.102
          ansible_ssh_private_key_file: /home/user01/vms/.vagrant/machines/vm2/virtualbox/private_key
      vars:
        ansible_user: vagrant
    aws:
      hosts:
        centos1: 
          ansible_host: 52.29.146.32
          ansible_ssh_private_key_file: /home/user01/ansible/LightsailDefaultKey-eu-central-1.pem
          ansible_user: centos
        centos2:
          ansible_host: 3.127.196.5
          ansible_user: centos
