---
- name: Create cAdvisor container
  docker_container:
    name: cadvisor
    image: "{{ cadvisor_image }}"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    published_ports: "{{ cadvisor_hostport }}:8080"

- name: Get infos on container
  docker_container_info:
    name: cadvisor
  register: output

- name: Print the status of the container
  debug:
    msg: "The cadvisor container status is {{ output.container['State']['Status'] }}"
  failed_when: "output.container['State']['Status'] != 'running'"

- name: Check that you can connect (GET) to {{ ansible_host }}:{{ cadvisor_hostport }} page and it returns a status 200 
  uri: 
    url: "http://{{ ansible_host }}:{{ cadvisor_hostport }}" 
    method: GET 
  register: _result 
  until: _result.status == 200 
  retries: 5 
  delay: 1