---
- name: Create cAdviser container
  docker_container:
    name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.35.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    published_ports: 8080:8080
