---
- name: Create dir for VictoriaMetrics storage
  ansible.builtin.file:
    path: /var/victoria-metrics/data
    state: directory
    mode: '0750'

- name: Create a VictoriaMetrics container
  docker_container:
    name: victoria_metrics
    image: "{{ victoria_metrics_image }}"
    recreate: true
    published_ports: "{{ victoria_metrics_host_port }}:8428"
    volumes:
      - /var/victoria-metrics/data:/victoria-metrics-data
