---
- name: create users
  ansible.builtin.user:
    name: "{{ item.key }}"
    shell: /bin/bash
    groups: "{{ item.value.groups }}"
  loop: "{{ lookup('dict', users_list) }}"

- name: set authorized ssh key
  ansible.posix.authorized_key:
    user: "{{ item.key }}"
    state: present
    key: "{{ lookup('file', '{{ path_to_users_ssh_keys }}/{{ item.key }}.pub') }}"
  loop: "{{ lookup('dict', users_list) }}"
