---
- name: setup docker-ce repo
  yum_repository:
    name: docker-ce-stable
    description: Docker CE Stable - $basearch
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    enabled: true
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: install docker-ce
  yum:
    name: docker-ce
    state: present

- name: install docker-ce-cli
  yum:
    name: docker-ce-cli
    state: present

- name: install containerd.io
  yum:
    name: containerd.io
    state: present

- name: enable and start docker
  systemd:
    name: docker
    state: started
    enabled: true
